version: '2'
services:
  builder:
    build: .
    image: summon-aws-secrets-builder
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/summon-aws-secrets/output
    environment:
      GOOS:
      GOARCH:

  tester:
    build: .
    image: summon-aws-secrets-tester
    ports:
      - "8080"
    command: './test-entrypoint.sh'
    volumes:
      - .:/summon-aws-secrets
